# Generated by Django 5.2.4 on 2025-07-30 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_productimage_image_url_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='my_app.category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(help_text='Address used for billing this order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_orders', to='my_app.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='my_app.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(help_text='Address used for shipping this order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_orders', to='my_app.address'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='my_app.productvariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='my_app.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='my_app.category'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(blank=True, help_text="Optional: Link image to a specific variant if it's variant-specific", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='my_app.productvariant'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='my_app.customer'),
        ),
    ]
