# Generated by Django 5.2.4 on 2025-08-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_memberprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='member_profiles/'),
        ),
    ]
